name: tfg_maria_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.8
  google_fonts: 6.2.1

  firebase_core: 3.6.0
  firebase_auth: 5.3.1
  cloud_firestore: 5.4.4

  flutter_riverpod: 2.6.1

  http: 1.2.2
  url_launcher: 6.3.1
  cached_network_image: 3.4.1
  shimmer: 3.0.0
  intl: 0.19.0
  flutter_dotenv: 5.2.1
  flutter_svg: 2.0.13
  flutter_tts: 4.0.2
  image_picker: 1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
